### ISSUE TITLE
Add ability to symlink custom directories from config.yml file.

### ISSUE THREAD

**Issue by AlexSkrypnyk** [beetboxvm/beetbox#1]
This is useful for per-project customisation of the beetbox.

**Comment by GROwen** [comment]
You should be able to create a project specific file (following the naming convention in beetbox.config.yml in [beetbox/ansible/playbook-provision.yml](https://github.com/drupalmel/beetbox/blob/master/ansible/playbook-provision.yml#L9)) ie project.config.yml

**Comment by thom8** [comment]
This functionality already exists -- https://github.com/drupalmel/beetbox/blob/master/ansible/tasks/create-symlinks.yml

you just need to add the following conf to config.yml

```
symlinks:
  - src: /path/to/src/in/box
    link: /path/to/link/in/box
    force: yes # (delete an existing directory or file before creating the symlink)
```
