### ISSUE TITLE
PHPCS/Coder role for Drupal?

### ISSUE THREAD

**Issue by Decipher** [beetboxvm/beetbox#182]
For the sake of the DrupalCon First Time Sprinters Workshop, we are planning on adding a section on setting up PHPCS and Coder for PHP linting; It'd be nice to somehow have something setup within BeetBox so that users of BeetBox can get everything setup nice and quick.

@alexdesignworks This might be up your alley?

**Comment by ivangrynenko** [comment]
@Decipher @alexdesignworks would be great to have a role for that. At the moment I use dcr_provision to activate @alexdesignworks DCR project in the local.Vagrantfile like this (check the dcr_provision line:

``` bash
# Provision box

      beet_sh = "#{vconfig['beet_home']}/provisioning/beetbox.sh"
      remote_sh = "https://raw.githubusercontent.com/beetboxvm/beetbox/master/provisioning/beetbox.sh"
      local_provision = "sudo chmod +x #{beet_sh} && #{debug_mode} #{beet_sh}"
      remote_provision = "sudo apt-get -qq update && curl -fsSL #{remote_sh} | sudo bash"
      dcr_provision = "cd #{vconfig['beet_base']} && composer require alexdesignworks/dcr && vendor/bin/dcr install"
      node.vm.provision "ansible", type: "shell" do |s|
        s.privileged = false
        s.inline = "if [ -f #{beet_sh} ]; then #{local_provision}; else #{remote_provision}; fi && #{dcr_provision}"
      end
```

**Comment by ivangrynenko** [comment]
Apparently to get the local.Vagrantfile to work, I use this code to enable it:

``` bash
# Load Vagrantfile.local.
# If you make a 'Vagrantfile.local' you can over-ride anything in this file.

include_vagrantfile = File.expand_path("./local.Vagrantfile", __FILE__)
load include_vagrantfile if File.exist?(include_vagrantfile)
```

**Comment by AlexSkrypnyk** [comment]
This Wiki describes how to use tasks to install DCR
https://github.com/beetboxvm/beetbox/wiki/Useful-tasks

**Comment by AlexSkrypnyk** [comment]
Working code:

Place into `.beetbox/tasks/post/dcr.yml`

```
---
- name: Install DCR and dependencies.
  composer:
    command: require
    arguments: alexdesignworks/dcr
    working_dir: "{{ beet_base }}"
  become: no

- name: Install DCR for current project.
  command: vendor/bin/dcr install
  args:
    chdir: "{{ beet_base }}"
  become: no
```
