### ISSUE TITLE
beetbox.sh provide beet repo as argument for testing in forks

### ISSUE THREAD

**Issue by AlexSkrypnyk** [beetboxvm/beetbox#272]
`BEET_REPO` variable is currently hardcoded to main beetbox repo URL.
When authoring roles there is a need to run role test on a fork of beetbox that has role's integration.

Proposed solution:
Allow providing repo URL as first optional argument. If argument is not provided, the repo URL will default to main beetbox repo URL.

This will change `circle.yml` for roles from this

```

---
dependencies:
  override:
    - bash <(curl -fsSL http://bit.ly/beetbuild)
test:
  override:
    - sudo cp ~/$CIRCLE_PROJECT_REPONAME/tests/config.yml /beetbox/.beetbox/config.yml
    - bash <(curl -fsSL http://bit.ly/beetbuild)
```

to this

```

---
dependencies:
  override:
    - bash <(curl -fsSL http://bit.ly/beetbuild) https://github.com/user/beetbox
test:
  override:
    - sudo cp ~/$CIRCLE_PROJECT_REPONAME/tests/config.yml /beetbox/.beetbox/config.yml
    - bash <(curl -fsSL http://bit.ly/beetbuild) https://github.com/user/beetbox
```
