### ISSUE TITLE
Who's up for Beetbox using Centos / RHEL?

### ISSUE THREAD

**Issue by christopher-hopper** [beetboxvm/beetbox#354]
When developing and testing code it is essential to have a local environment that matches the intended target as closely as possible. The PHP binaries installed on Debian / Ubuntu are not the same as those you'll get for CentOS / RHEL. Nor are many or all of the other key elements of the web stack. 

Many of the Ansible galaxy roles relied upon by Beetbox already support both Debian and RHEL based distributions. So they will work nicely when run on Ubuntu or CentOS without needing a lot of work.

The Ansible playbooks and roles for Beetbox itself all assume Ubuntu as the target. Nothing wrong with that by the way, as this is the target distribution. 

We could open Beetbox up to support both Debian and RHEL based distros by adjusting some of the patterns used in the Beetbox Ansible code to be more distro aware. 

Imagine this:

    vagrant box add beet/centos

## Example

- Use Ansible `package` instead of `apt`
- Set variable defaults for paths that are aware of the distro
- Use package name defaults that are aware of the distro

Here's some sample Ansible code that installs the Vi Improved text editor. It will work on either Ubuntu or Centos:

```yml
- name: "Install Vi Improved."
  package:
    name: "{{ (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') | ternary('vim-enhanced', 'vim') }}"
    state: latest
```
