### ISSUE TITLE
Copy mysql config to .beetbox/config.yml

### ISSUE THREAD

**Issue by AlexSkrypnyk** [beetboxvm/beetbox#46]
It is not obvious when you start working with beetbox what the most expected options are.

I suggest to copy these lines from `beetbox.config.yml` to `config.yml`

``` yaml
beet_mysql_user: beetbox
beet_mysql_password: beetbox
beet_mysql_database: "beetbox_{{ beet_project }}"
```
