### ISSUE TITLE
Add Twig C extension

### ISSUE THREAD

**Issue by Decipher** [beetboxvm/beetbox#64]
Yet another Pear package we should have by default; Twig C extension: http://twig.sensiolabs.org/doc/installation.html#installing-the-c-extension

**Comment by thom8** [comment]
Note: 

> Using PEAR for installing Twig is deprecated and Twig 1.15.1 was the last version published on the PEAR channel; use Composer instead.

**Comment by Decipher** [comment]
Will take a look at it this week as I will be working on front-end on a D8 site.

**Comment by thom8** [comment]
I'd recommend adding this as a project dependency with composer  `composer require twig/twig:~1.0`

however it could also be included as a custom task --

```
---
- name: Install Twig PHP package with composer.
  composer:
    command: require
    arguments: twig/twig:~1.0
    working_dir: "{{ beet_base }}"
  become: no
```
